# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/textplumber',
                'doc_host': 'https://polsci.github.io',
                'git_url': 'https://github.com/polsci/textplumber',
                'lib_path': 'textplumber'},
  'syms': {'textplumber.core': {'textplumber.core.foo': ('core.html#foo', 'textplumber/core.py')}}}
