"""Helper functions for textplumber."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/95_core.ipynb.

# %% auto 0
__all__ = ['pass_tokens']

# %% ../nbs/95_core.ipynb 3
def pass_tokens(tokens):
	""" Pass through function to pass pre-tokenized input to CountVectorizer or TfidfVectorizer. """
	return tokens
