"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['pass_tokens']

# %% ../nbs/00_core.ipynb 3
def pass_tokens(tokens):
	""" Pass through function to pass pre-tokenized input to CountVectorizer or TfidfVectorizer. """
	return tokens
