"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_textcleaner.ipynb.

# %% auto 0
__all__ = []

# %% ../nbs/05_textcleaner.ipynb 3
from lxml import html
from sklearn.base import BaseEstimator, TransformerMixin
